package main

const (
	I_NOP = iota & 0xF
	I_LDA
	I_ADD
	I_OUT
	I_HLT
)

var microcode = []int64{
	PC_OUT | MEM_ADDR_IN, PC_INC | MEM_OUT | INS_REG_IN, 0, 0, 0, 0, 0, 0, // NOP
	PC_OUT | MEM_ADDR_IN, PC_INC | MEM_OUT | INS_REG_IN, INS_REG_OUT | MEM_ADDR_IN, MEM_OUT | REGA_IN, 0, 0, 0, 0, // LDA
	PC_OUT | MEM_ADDR_IN, PC_INC | MEM_OUT | INS_REG_IN, INS_REG_OUT | MEM_ADDR_IN, MEM_OUT | REGB_IN, ALU_OUT | REGA_IN, 0, 0, 0, // ADD
	PC_OUT | MEM_ADDR_IN, PC_INC | MEM_OUT | INS_REG_IN, REGA_OUT, OP_OUT, 0, 0, 0, 0, // OUT
	PC_OUT | MEM_ADDR_IN, PC_INC | MEM_OUT | INS_REG_IN, CLOCK_HALT, 0, 0, 0, 0, 0, // HLT
}
